import './globals.css';

import { Plus_Jakarta_Sans as FontSans } from 'next/font/google';

import { cn } from '@/features/shadcn/utils';

//* Components
import Navbar from '@/features/ui/elements/Navbar';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Co space working',
  description: 'Generated by create-next-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      {/* dark - light */}
      <body
        className={cn(
          'm-auto min-h-screen max-w-[1440px] bg-white-10 font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
