import Head from 'next/head';
import Container from '~/features/ui/components/Container';
import DetailSection from '~/features/ui/featurePages/DetailSection';
import HeroSection from '~/features/ui/featurePages/HeroSection';
import GoSpaceSection from '~/features/ui/featurePages/GoSpaceSection';
import Navbar from '~/features/ui/navbar';
import Footer from '~/features/ui/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Co working space</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden bg-white-10">
        <Container className="py-5">
          <Navbar />
        </Container>
        <Container className="py-[120px]">
          <HeroSection />
        </Container>
        <Container className="py-[112px]">
          <DetailSection />
        </Container>
        <Container className="py-20">
          <GoSpaceSection />
        </Container>
      </main>
      <footer className="bg-black-80">
        <Container className="py-[64px]">
          <Footer />
        </Container>
      </footer>
    </>
  );
}
