import Head from 'next/head';
import Container from '~/features/ui/components/Container';
import Navbar from '~/features/ui/navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Co Working Space</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white-10">
        <Container className="py-5">
          <Navbar />
        </Container>
      </main>
    </>
  );
}
