import Head from 'next/head';
import Container from '~/features/ui/components/Container';
import DetailSection from '~/features/ui/homepages/DetailSection';
import HeroSection from '~/features/ui/homepages/HeroSection';
import MarqueeHero from '~/features/ui/homepages/MarqueeHero';
import TestimonialSection from '~/features/ui/homepages/TestimonialSection';
import Navbar from '~/features/ui/navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Co Working Space</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white-10">
        <Container className="py-5">
          <Navbar />
        </Container>
        <Container className="py-[120px]">
          <HeroSection />
        </Container>
        <Container>
          <MarqueeHero />
        </Container>
        <Container className="py-[112px]">
          <DetailSection />
        </Container>
        <Container className="bg-gradient-2 px-0 py-[64px]">
          <TestimonialSection />
        </Container>
      </main>
    </>
  );
}
